### ISSUE TITLE
19uu dates start/end for Primo

### ISSUE THREAD

**Issue by jallibunn** [Orbis-Cascade-Alliance/harvester#92] opened 2017-08-08 16:53 UTC
An item (http://cdm16085.contentdm.oclc.org/cdm/ref/collection/p15013coll4/id/207) in a set contributed by SOU has a date of 19uu. The Primo version does not have the dc:date.start and dc:date.end properties, which should be 1900 and 1999 respectively.
@cwyant-alliance

**Comment by ewg118** [comment] 2017-08-08 17:06
Duplicate of #85

**Closed as completed by ewg118** 2017-08-08 17:06 UTC

**Comment by jallibunn** [comment] 2017-08-08 17:40
So it is. And now you have more than one example to text a fix!
@cwyant-alliance
